### PR TITLE
Game frontend - Create Game - Page 1 - Game Name, Type and Image

### PR DESCRIPTION
**Pull request by WarrenK-design**
I don't expect a review on this tonight I know its late, can demo on localhost tomorrow. 

This is first page in the create game flow.  User has to select a name (defaults to one already), a game type and a image.  Default names for issue we discussed about sanitising inputs on backend. 

The ```GameCreationOptionsCard``` component also has a new prop to disable the next button if all fields have not been completed. 

image
image
image
image

### CODE REVIEW

**Review by DaraghK93 — COMMENTED** [review]
Hi Warren, looks great. really coming together. 

Just two things that worry me slightly. one being the drop down for names. it's a good work around for people calling the games ridiculous things. it may get a bit confusing if they have a few games called the same thing however. we've discussed having more options in the drop down, so this could work as well.

One main thing i noticed was that it's kind of hard to see which image is selected here
Screenshot 2022-11-10 at 20 08 04
not suer what the workaround is. maybe make the outline a little thicker? I found it quite hard to see at the start. also is there any point in telling them what the image they're picking is for, or do you think people will just guess that will be the game logo?

**Comment by WarrenK-design** [comment]
> Hi Warren, looks great. really coming together.
> 
> Just two things that worry me slightly. one being the drop down for names. it's a good work around for people calling the games ridiculous things. it may get a bit confusing if they have a few games called the same thing however. we've discussed having more options in the drop down, so this could work as well.
> 
> One main thing i noticed was that it's kind of hard to see which image is selected here Screenshot 2022-11-10 at 20 08 04 not suer what the workaround is. maybe make the outline a little thicker? I found it quite hard to see at the start. also is there any point in telling them what the image they're picking is for, or do you think people will just guess that will be the game logo?

Hi Daragh yeah if we can come up with few more names or maybe a random name generator on backend route? For now though yeah might just be the workaround. 

Yeah I'm not sure I may leave it for now and we could see from evaluation if people get it or not, I've been looking at it too long to know if people will get it or not. 


Added a larger border to this. 
image

**Review by DaraghK93 — APPROVED** [review]
That looks a lot better, and will be a lot easier to spot.

I'll approve this, we can chat about the other things tomorrow/next week. great work

**Review by BearachB — APPROVED** [review]
100% I'd agree with @DaraghK93's concerns on the league names. Happy to go with your solution for the moment but need to have a think about how to implement it to give users some choice. Maybe just validate the names using a name library? Haven't looked for this but surely React has libraries for this exact scenario?

**Comment by WarrenK-design** [comment]
> 100% I'd agree with @DaraghK93's concerns on the league names. Happy to go with your solution for the moment but need to have a think about how to implement it to give users some choice. Maybe just validate the names using a name library? Haven't looked for this but surely React has libraries for this exact scenario?

Grand job, yeah I do agree it is a problem alright but again something we could sink hours into. I think we put it on back burner for now anyway.

**Pull request merged**
