### PR TITLE
Backend update portfolio schema

### PR DESCRIPTION
**Pull request by joeycor92**
Just a quick update to the portfolio schema in line with Daragh's updates on the league schema and user schema. The routes will need to be updated in the next PR which will be to create a create portfolio service.

image

Not getting any errors.

### CODE REVIEW

**Review by BearachB — APPROVED** [review]
That seems to simplify it a bit! good work.

I'll be needing to access the user's holdings when I'm querying the recommender system service so good to see a simpler Mongo model for it.

**Review by DaraghK93 — CHANGES_REQUESTED** [review]
Looks good Joey, just one thing onthe valueHistory field. we discussed a CRON job getting all the end of day values through calculating the holdings + remainder, so i think it should just be
valueHistory: [{date, endOfDayValue}]

**Comment by joeycor92** [comment]
> Looks good Joey, just one thing onthe valueHistory field. we discussed a CRON job getting all the end of day values through calculating the holdings + remainder, so i think it should just be valueHistory: [{date, endOfDayValue}]

Good call. As discussed this will just be the total value updated at the end of each day.

**Comment by joeycor92** [comment]
Updated now to remove 'required' for totalValue as this is a calculated field.

**Review by DaraghK93 — APPROVED** [review]
looks great, thanks for the change

**Pull request merged**
