### PR TITLE
React router configuration. Installed react router

### PR DESCRIPTION
**Pull request by joeycor92**
Hi Folks,

Could you both review and let me know that you are happy with the changes? 

Used
npm install react-router-dom@6

Let me know if you have any issues.

### CODE REVIEW

**Comment by WarrenK-design** [comment]
Delete the body of App with this commit and just return the router in App.js, people can add routes then for screens once its setup.

**Review by WarrenK-design — CHANGES_REQUESTED** [review]
Delete the body of App with this commit and just return the router in App.js, people can add routes then for screens once its setup then.

**Comment by joeycor92** [comment]
> Delete the body of App with this commit and just return the router in App.js, people can add routes then for screens once its setup then.

Have made this change now for your review.

**Review by WarrenK-design — APPROVED** [review]
Looks good!

**Pull request merged**
