### PR TITLE
Game updates and bug fixing

### PR DESCRIPTION
**Pull request by beckskelly**
- Sorted pagination in the porrtfolio tables, only shows up if you have over 5 stocks and is appropriate to the amount of stocks in your portfolio up to 15
- Removed all holdings with a value of 0 in holdings 
- separated price graph from individual stock page to be reused in portfolio page
- changed so absolute change and percentage change are dependant on what timescale chosen on individual stock page (day, month, year etc)
- fixed graphs to only show min and max value so you can see range better
- got rid of decimal points on graphs
- Y axis now shows currency in correct format
- CHANGE CXHANGE in portfolio now showing actual values
- fixed absolute change bug in individual stock page, minus symbol now comes before  $ sign
- Cancel order now working on transactions table
- Added scrollbars back in
- Tab at top of page now says "FinOptimise" instead of "React App"
- fixed BUY / SELL/ ALL buttons on transaction history component
- information buttons added to transactions and holdings
- Linked in daily data to individual stock page
- Fixed dates on price graph, now changes when resized and loads properly too
- button icons "browse more stocks" "view leaderboard"
- back button on trade page also logo is a button that goes back now
- updated "make a trade now" to ingame stocks page link -> portffolio, timeline, valueline
- key error on game portfolio page gone
- logo no longer enormous on individual stocks page

TO DO:
- Graph a tiny bit smaller on individual stock page desktop view... damiens comment, worth doing? i started and it annoyed me

### CODE REVIEW

**Review by WarrenK-design — CHANGES_REQUESTED** [review]
Hi Becks, 

Looks good few things, let me know when to do full review just first few comments 

# Portfolio 
When I have nothing in portfolio it seems to have gone back to old way. 
image
Should still be showing this like on live website I think promoting them to trade. 
image

# Holding 0 
This does look better alright but if I just have a limit order I can see people being confused because my spending power has gone down, could you add in info button here just maybe explaining what a holding is? Maybe one for Transactions too. 
image

**Comment by joeycor92** [comment]
A lot in this so I could end up splitting up my comments.

The 1 day values are coming in backwards from the backend now so you might need to flip them. As well as that, the graph probably needs to start lower than the lowest value, it kind of just looks like the stock has bottomed out.
image

**Comment by joeycor92** [comment]
Quick one might be that this should say No completed Sells, as there are transactions.
image

**Comment by joeycor92** [comment]
image
Not only purchases, also sales.

**Comment by joeycor92** [comment]
This is likely to be a conflict as Warren added in sector. So maybe just take a look at what his looks like with yours, you might need to do some moving around.
image

**Review by joeycor92 — CHANGES_REQUESTED** [review]
Code looks great and happy out. When those changes are made I'll approve. Thanks again. Serious work and fair play. Cosmetically it's just looking unreal.

**Comment by beckskelly** [comment]
@joeycor92 thank you for the review
- Fixed 1 day prices no longer backwards
- Resolved conflict with warrens branch
- Updated modal
- fixed error message for transactions
image

left to do:
- increase range of graphs as looks a little silly

**Comment by beckskelly** [comment]
Managed to increase range, @joeycor92 if youd like to review again

**Review by WarrenK-design — CHANGES_REQUESTED** [review]
Hi Becks, 

Good work here lot gone into it,  we may get 3 reviewers on this though lot here and bit risky towards end. @DaraghK93 @BearachB or @caolan-power maybe if yous could have quick glance too. 

# Transaction Table 
If you can just vertically align this. 
image

# Holding Table 
Still asks if I want to see 10 even though there is only 6 stocks in my portfolio. 
image
If I have 10 it shows 10 twice. 
image
Same for 15. 
image

I have 15 stocks in my portfolio. 
image
When I go to page 3, then click "Show all" then all my stocks disappear. 
image
Exact same error happens with the transaction table too looks like I have none but actually have 18. 
image

# Cancel Order 
I have two orders in my pending. 
image
I cancel 1 it refreshes page, go back down and the order is gone. 
image
I click cancel on the tesla order now it does the refresh/loading spinner but when I go down to it Tesla is still there. 
image
I click cancel on Tesla again as its still there and then I get this change. 
image

# Icons - Mobile 
On mobile these dont look great, if its too awkward at this stage I think we get rid of them 
image

# Stock Discovery 
When you load it for first time on mobile getting this line here, not sure if its your branch or a merge put pull from master its not on live site, looks out of place. 
image

# Back to Stock Info 
I think this might look better as just ```view stock information``` or just ```stock details``` maybe. 
image
Or if it is a back button maybe up here? Just looks really out of place. 
image
image

# Make A Trade Now
In description you mentioned this is a link but not seeing it here. 
image
image

**Comment by beckskelly** [comment]
cheers @WarrenK-design just noting these as I get through them still a bit to do 

- cancel order bug should be fixed by updating success state
- all scrollbars gone under 800px
- centering issue on table is fixed

**Comment by WarrenK-design** [comment]
Fixed the back button. 
image

**Comment by beckskelly** [comment]
- bug where you hit select all button when youre on page 2/3 should be resolved now

**Comment by beckskelly** [comment]
- tables now should not show you view 10 when you only have 7 stocks in portfolio etc

**Comment by WarrenK-design** [comment]
Fixed the icons on mobile. 
image

**Comment by beckskelly** [comment]
- all button bug resolved for 15 and 10 stocks in transactions and holdings

**Comment by beckskelly** [comment]
@WarrenK-design @joeycor92 message pops up when you cancel a transaction and I think that concludes my bugs... for now

**Review by WarrenK-design — CHANGES_REQUESTED** [review]
Just quick one as I am still going through it, for the holdings and portfolio table, add heading name and stock symbol onto index?
image
image

**Review by joeycor92 — APPROVED** [review]
Feel like this is finally there.

A massive PR to finish us off. Happy to approve. 

Well done to everyone who had input on this one, great work.

Tried my best to break but couldn't seem to do it.

**Comment by beckskelly** [comment]
thanks to all for help with this branch!

**Pull request merged**
