### PR TITLE
Game frontend create game my game page

### PR DESCRIPTION
**Pull request by WarrenK-design**
Start of the froentned for the game section. 

A new route on the frontnend "/game" has been added and is avaiable to signed in users through "Game" button in the nav bar. 

The screen has two sections ```My Games``` and ```Join a Game```, tis PR deals only with ```My Games```. 

At the top of the page is the ```Create a Game``` button this is next step I will work on. 

In the body is the users games split up into ```Active```, ```Scheduled``` and ```Complete``` using the logic we discussed @DaraghK93. 

Fake games have been made for now using an array in the ```GameScreen.js``` file, this is format too we discussed for getting a request with an array of ```active``` and ```inactive``` games. 

The images for the games are stored in the ```public``` folder as there are only 5 images used, 4 the user can select and then ` for the create game card to make it stand out from the rest. 

The component for the horizontal scroll for the ticker Cards has been deleted, I needed it for the game cards so got rid of the stock specific stuff and made a new component based off it in the folder ```widgets/SideScrollMenu```, updated the stocks page too to use it. It uses [composition in react](https://reactjs.org/docs/composition-vs-inheritance.html) so we can reuse it again wherever if needed.  

***Phone***
image

***Desktop***
image

### CODE REVIEW

**Review by beckskelly — CHANGES_REQUESTED** [review]
Looks good Warren, very smart solution refactoring the side scroller.

just one small change on the frontend, a bit more space between these elements would be better I think

image


Also on a side note, this is a big PR. It's something you criticized my own PR's in the past for, I've done my best possible to review it thoroughly and I appreciate most of the new components are straight forward - are we doing bigger PR's now? 

Like most of this code looks good but as far as what I can interact with I can only see a create game button, active/ scheduled games that dont lead anywhere. Theres stuff like "ScreenSelectionRadioButton" that I cant get at to test, and yet are in this PR. Unless I'm wrong?

**Comment by WarrenK-design** [comment]
Cheers @beckskelly 
> Looks good Warren, very smart solution refactoring the side scroller.
> 
> just one small change on the frontend, a bit more space between these elements would be better I think

Put in a padding for it. 
image

> Also on a side note, this is a big PR. It's something you criticized my own PR's in the past for, I've done my best possible to review it thoroughly and I appreciate most of the new components are straight forward - are we doing bigger PR's now?

That's fair yeah I wasn't sure how to break it up fully to be honest with you, this is the epic I am working off https://github.com/DaraghK93/stockApp#workspaces/group-project-632d926d42342800106ed738/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTA2MzQ3 if you want we can break this down further? 

> Like most of this code looks good but as far as what I can interact with I can only see a create game button, active/ scheduled games that dont lead anywhere. 

Yeah again sorta the last point too I was going to put in screens for them but stopped because PR was getting big.  I can delete links on the cards if you want before I merge and just add them in next PR? 

> Theres stuff like "ScreenSelectionRadioButton" that I cant get at to test, and yet are in this PR. Unless I'm wrong?

Should be able to test everything, the game screen broken down as below. 

1. ScreenSelectionRadioButton
image

2. CreateGameCard 
image

3. ActiveInactiveScheduledGames
image

4.  GameCard 
image

If want I can break it down PR's by component instead of full page? Was just sorta hard to viz how all glued together without them all but can do in future, I know a lot of code can be pain to review.

**Comment by beckskelly** [comment]
@WarrenK-design  By component might be a bit better in the future yes, unless its just a small component. I appreciate its difficult to overall visualise whats going on piece by piece, but yeah I got a bit confused with the amount of code in, which is why I thought i couldnt test all the components, my mistake! 

Just leave the links in for now as I imagine youll have that sorted in your next PR? also I think the new change is good, the bit of padding separates the info a bit visually.

also just spotted this on the stock discovery page, looks like you forgot to apply a class to the lower rows

image

**Comment by WarrenK-design** [comment]
> also just spotted this on the stock discovery page, looks like you forgot to apply a class to the lower rows
> 
> image

Grand job fixed that there.

> Just leave the links in for now as I imagine youll have that sorted in your next PR? 

Kept in the create game ne but the actual game card is the one your are prototyping do deleted that link for now as will just keep going to the 404 page. 

> By component might be a bit better in the future yes, unless its just a small component. 

Ok I may give you a shout on what the PR's will be then for next few before I get too far.

**Review by beckskelly — APPROVED** [review]
Sound! approved on my end

**Review by DaraghK93 — APPROVED** [review]
looks great Warren. The games page should work well with the backend.

**Pull request merged**
