### PR TITLE
sprint retro week 6

### PR DESCRIPTION
**Pull request by beckskelly**

### CODE REVIEW

**Review by BearachB — APPROVED** [review]
Good stuff! Just be careful in future that you don't edit previous retrospectives. I know the content is the same but if you're submitting a PR for this it should only include the week6.md file!

**Comment by beckskelly** [comment]
@BearachB yes, sorry about that! will be more careful next time

**Review by caolan-power — APPROVED** [review]
Looks good

**Review by WarrenK-design — APPROVED** [review]
Looks good

**Pull request merged**
