### PR TITLE
Splash page 2

### PR DESCRIPTION
**Pull request by caolan-power**
Next iteration of the splash page.

Check for structure and wording and stuff now.

Mostly there structure wise now I think just need to add pictures of the app into the carousel want nice ones from the game etc.

Screenshot 2022-12-01 at 12 54 57
Screenshot 2022-12-01 at 12 55 09
Screenshot 2022-12-01 at 12 55 18

### CODE REVIEW

**Review by joeycor92 — CHANGES_REQUESTED** [review]
Straight off the bat:

1. Decrease the size of the Logo in desktop


2. Make sure these go across the whole way
image

3. Maybe on desktop make these smaller and maybe put them side by side. Can probably copy what's done on the actual stock page.
image

**Review by BearachB — APPROVED** [review]
@caolan-power great start for this page! 

Lots of stuff that needs to be addressed however I'm happy to approve this as a starting point. If I'm not working on it next I'll give you the list of changes I'd make, still gathering them.

**Comment by beckskelly** [comment]
@caolan-power great start to this page, thanks for fixing footer, cards, thumb, scrollbar and logo size as per the discord chat. Welcome to the dark side of frontend development!

**Review by beckskelly — APPROVED** [review]

**Review by joeycor92 — APPROVED** [review]
Approving for now. Few updates to be made yet but great start.

**Pull request merged**
