### PR TITLE
Created the individual news cards

### PR DESCRIPTION
**Pull request by WarrenK-design**
They change oriented by row or col based upon phone or desktop. New sentiment badge component also added.
Image size is issue used tricky image in example below, on phone to keep ratio this is what looks like, what do we think? Was trying for figma design but the text in figma was actually tiny when used that CSS. 

Note dates be fixed in higher component which data passed from. 
***Desktop***
image
***Phone - Iphone SE***
image
***Prototype***
image

### CODE REVIEW

**Comment by beckskelly** [comment]
You could get away with making them smaller, see snip from the business times 
image

**Comment by WarrenK-design** [comment]
New mobile cards
image

**Review by beckskelly — APPROVED** [review]
Looks good to me! I like the smaller card better yeh, I think we can do things a lot smaller on the mobile than we realise in general

**Review by joeycor92 — APPROVED** [review]
Think it looks class. As mentioned, we will need to update the timestamp to a nicer format. Good call from Becks to make smaller. Happy with this with the condition that the timestamp is changed at a later date.

**Pull request merged**
