### PR TITLE
Registration form - DOB and location fields removed, tickbox added for age verification, user schema updated for 

### PR DESCRIPTION
**Pull request by BearachB**
# Changes
- DOB field removed from registration form
- Location field removed from registration form
- Age verification checkbox added (with required attribute) to registration form
- User schema updated (overeighteen attribute added) - This may not actually be needed
- User controller updated to account for overeighteen attribute 

---
# Note:
I have left the DOB and location fields on the controllers in for now, but have commented them out. I will be adding password validation into this branch later today, however wanted to get these changes in so that it's not all in one PR.

---

# Screenshots:

## DOB and location fields removed
image

## Age verification checkbox
image

### CODE REVIEW

**Review by beckskelly — CHANGES_REQUESTED** [review]
Looks good, I think its much better with less fields to register, and the checkbox is clever!

Try the first and last name side by side in the form, also I'd change the text for the checkbox to something more accesible "I am over 18 years of age" maybe? 

Would it be worth making the checkbox more obvious, highlighting that message with a blue background or something?

**Comment by BearachB** [comment]
> Try the first and last name side by side in the form

True that would look better. I'll add that to the list, but for now I wasn't changing the formatting/CSS. Just functional changes.

> also I'd change the text for the checkbox to something more accesible "I am over 18 years of age" maybe?
As in just update the text from "By ticking this box I certify that I am over 18 years of age." to "I am over 18 years of age"?

> Would it be worth making the checkbox more obvious, highlighting that message with a blue background or something?
I can mock it up to see, but I think it'll look a bit off given that the other fields are all plain black and white at the moment.

**Review by WarrenK-design — CHANGES_REQUESTED** [review]
Getting warning here. 
image
Remove this console log 
image

A lot of changes are just semi colon removes what was reason for this?
image
All of these types of console logs too can you remove them, they wont make sense in logs will just be a string of random numbers will make it hard to debug in cloud watch. Log maybe if something goes wrong or operation successfully completes only.  
image

Can we all just agree on this now maybe and either delete it or keep it. Will save you lot of hassle commenting out code. 
image

**Comment by BearachB** [comment]
> A lot of changes are just semi colon removes what was reason for this?

That's a result of using Prettier to format the .js files in VS Code. (Shift + Alt + F). I find it's easier to read if all the files I'm working on have exactly the same formatting.

Addressing your other comments now! Cheers

**Comment by beckskelly** [comment]
@BearachB   I can see one issue with using a formatter like that, it states that a lot of the code has been changed when it technically hasnt, and could make it difficult to see the changes down the line, especially with lots of lines, like in your case, 400+. Its better practise to respect the code in place in general

**Comment by BearachB** [comment]
> I can see one issue with using a formatter like that, it states that a lot of the code has been changed when it technically hasnt, and could make it difficult to see the changes down the line, especially with lots of lines, like in your case, 400+. Its better practise to respect the code in place in general

@beckskelly Very true. Caused a problem right here in this PR. One of @WarrenK-design's comments about console logs wasn't actually code I had written, but because I had used a formatter on it it looked like I had written the entire file. Definitely an issue to raise with the entire team.

**Comment by BearachB** [comment]
> I think maybe we just format code ourselves, the "Files Changed" section was quite hard to read for this PR. Was hard to tell what code you actually wrote.

Good point, I had only realised after I had made the PR. Will avoid formatting entire files unless I'm actually changing them.

> @WarrenK-design Getting warning here.

My apologies that was a silly mistake to leave in, won't happen again.

> @WarrenK-design Remove this console log

Done.

> @WarrenK-design Can we all just agree on this now maybe and either delete it or keep it. Will save you lot of hassle commenting out code.

Deleted out once and for all. Can always check back on the branch if this needs to be ported over at some point (I'm doubtful if this would ever be the case though).


---

All comments addressed. Updates pushed

**Review by WarrenK-design — CHANGES_REQUESTED** [review]
Can you do a npm uninstall on this package, think was only used in login page. 
image

**Comment by BearachB** [comment]
> @BearachB you aint addressed my comments so I'm just gonna ask again, are you doing another PR to change the appearance (form fields side by side) or just leaving it for now? I would change it while youre at it now so we can sign off on the page. and how about that checkbox text?

[I already replied this this above](https://github.com/DaraghK93/stockApp/pull/352#issuecomment-1281036558). I can look at it tomorrow if everyone wants me to, but it hadn't been discussed so today I was only addressing the changes we had discussed on Friday.

> True that would look better. I'll add that to the list, but for now I wasn't changing the formatting/CSS. Just functional changes.

**Comment by WarrenK-design** [comment]
> > Can you do a npm uninstall on this package, think was only used in login page. image
> 
> I thought we were going to be leaving the package in, as I thought we were going to be having country as an optional piece of info the users could select in the profile section?

Grand job if its that package we are using then leave it in.

**Review by WarrenK-design — APPROVED** [review]

**Comment by beckskelly** [comment]
Ok grand, I'll approve, we can revisit the appearance at a later stage

**Review by beckskelly — APPROVED** [review]

**Comment by BearachB** [comment]
> Ok grand, I'll approve, we can revisit the appearance at a later stage

@beckskelly It is a good idea, I'll look at it tomorrow/bring it to the whole team! Just don't want to waste time unnecessarily at the minute as there's a lot of stuff that needs to be done this week. You're right though it would be nice to fully close it out and not have to go back to it.

**Pull request merged**
