### PR TITLE
Added directory for sprint retrospectives, along with the sprint retr…

### PR DESCRIPTION
**Pull request by BearachB**
…ospective for week 3 in the Stop, Start, Continue format

### CODE REVIEW

**Comment by BearachB** [comment]
@paul-kelly-dit. For the sprint retrospective document, is .md format OK?

**Review by beckskelly — CHANGES_REQUESTED** [review]
Looks good! A backup task to work on in case of slowness or depending on another coder is a suggestion

**Comment by BearachB** [comment]
@joeycor92 @beckskelly good points by all! I've amended the retro and will re-push now!

**Review by joeycor92 — APPROVED** [review]

**Review by DaraghK93 — APPROVED** [review]
looks great, thanks for filling out

**Pull request merged**
