### PR TITLE
Mvp backend ESG Data Ingress LF

### PR DESCRIPTION
**Pull request by DaraghK93**
This is the Lambda function that will gather the ESG data from ESG enterprise's API. It then sends this data down to our database and updates the "esgrating" field of the matching stocks. We will have this running every week or 2 weeks.

I think this is ready to be deployed to amplify. I've been mock running the function and it's working, however I may need to change the timeout and the permissions once it's up there. Let me know if there's anything obvious missing

### CODE REVIEW

**Review by WarrenK-design — APPROVED** [review]
Looks good! The CRON event created in the cli already yeah?

**Comment by WarrenK-design** [comment]
Actually could you create a quick README in the folder just if I was to run it locally do I need to setup any environment variables locally/change anything?

**Review by WarrenK-design — CHANGES_REQUESTED** [review]
Actually could you create a quick README in the folder just if I was to run it locally do I need to setup any environment variables locally/change anything? Like can I use my local MongoDB instance with this, dont want to check this branch out run it and it goes to main one.

**Review by caolan-power — APPROVED** [review]
Looks good

**Comment by DaraghK93** [comment]
> Actually could you create a quick README in the folder just if I was to run it locally do I need to setup any environment variables locally/change anything? Like can I use my local MongoDB instance with this, dont want to check this branch out run it and it goes to main database.

Thanks for this. I've added that. I also added the CRON event Through amplify CLI to go once a week on a monday morning.

@caolan-power thanks for showing me that. I increased the timeout there so should be good to go

**Review by WarrenK-design — APPROVED** [review]
Looks good

**Pull request merged**
