### PR TITLE
Scss global variables

### PR DESCRIPTION
**Pull request by beckskelly**
Moved all the variables into their own file, changed all static values (px) to rem

### CODE REVIEW

**Review by WarrenK-design — CHANGES_REQUESTED** [review]
I like this but can we break it up with comments somehow. or something by end of project can see this file being quite big 
```
/* File Name One Variables Used */
varOne= 
VarTwo= 
/* File Name Two Variables Used */
myVar=
nextVar=
/* File Name Three Variables Used */
somethingElse=
```
Or an alternative is to have 1 global variables file, this holds styles which are used throughout the project, things like primary, secondary colour. 
If a variable is then used only for a specific component then it should be in its own variables file or just defined within that file. Something like this below or just have definition of local vars in the scss file they are used maybe? 
```
scss/
      globalVariables.scss
      /sentimentComponents/
                     sentimentBadge.scss
                     sentimentBadgeVariables.scss 
```

**Review by joeycor92 — APPROVED** [review]
All much better with REMs instead of fixed values. I can see what Warren means, it's good to have as many comments as possible throughout just especially for us reviewing. Great stuff.

**Comment by beckskelly** [comment]
@WarrenK-design I'll defo add in comments as to where all these variables have gone, it will aid us with readability down the line.

For variables in a specific component, I think it's better to have them all in just the one global variables file, as from a point of view of design, a reduced colour palette is best. So for example, your positive, neutral and negative colours for your badges would be resued again in the graphs.

I am reading around extracting the variables at the moment so they can be used in the graphing package easily, as currently they can't without just hardcoding into the code. Because of this, I don't think we will have more than 20 colours max, (if we do shoot us and our awful rainbow app) and I think they should stay in the one global_variables file.

**Comment by WarrenK-design** [comment]
> @WarrenK-design I'll defo add in comments as to where all these variables have gone, it will aid us with readability down the line.
> 
> For variables in a specific component, I think it's better to have them all in just the one global variables file, as from a point of view of design, a reduced colour palette is best. So for example, your positive, neutral and negative colours for your badges would be resued again in the graphs.
> 
> I am reading around extracting the variables at the moment so they can be used in the graphing package easily, as currently they can't without just hardcoding into the code. Because of this, I don't think we will have more than 20 colours max, (if we do shoot us and our awful rainbow app) and I think they should stay in the one global_variables file.

Ah yeah for colours I think this is fine to have things like "positive" "negative" "neutral" in the global but just thinking down the line from reading into scss, variables can be [more than colours](https://sass-lang.com/documentation/values) and they do have [scope ](https://sass-lang.com/documentation/variables#scope). I don't think defining everything in global scope if we really get into using it is best approach, if a variable is only used in one place should be scoped to that file and not in the global scope.

**Comment by beckskelly** [comment]
@WarrenK-design  Ok cool! All good points especially on variables not just being colours and their scope. As I intend on using the colours you defined in your news sentiment scss file (and so will Caolan) I am moving them to the global_variables file, but I will also include a readme comment at the top explaining that if a variable is used in one place only to use the structure as suggested in your initial comment.

**Comment by beckskelly** [comment]
@WarrenK-design is this explanatory enough? 
image

**Review by joeycor92 — APPROVED** [review]
I would think that's probably enough detail that you have their now so I'm happy with it.

**Review by WarrenK-design — CHANGES_REQUESTED** [review]
Yep nearly perfect but if doing readme do it in README.md format not in comments, so in file ```src/scss/README.md``` bit handier to update down the line than comments.

**Comment by beckskelly** [comment]
@WarrenK-design Grand! added the README.md

**Review by WarrenK-design — APPROVED** [review]
Looks good!

**Pull request merged**
