### PR TITLE
Database secure credentials 

### PR DESCRIPTION
**Pull request by WarrenK-design**
The database credentials in the Express app are now retrieved the same way as in the other lambda functions through AWS parameter store. 

If the value of the env variable ```ENVIRONMENT``` is ```prod``` then it will retrieve the production database credentials from AWS parameter store. 

If the value of the env variable ```ENVIRONMENT``` is ```dev``` then it will retrieve the database credentials from a local ```.env``` file. 

We all need to have a ```.env``` file under ```src``` with the contents below, have added this info to ```README.md``` too. 

```
ENVIRONMENT=dev
MONGO_URI=mongodb://localhost:27017/dev
JWT_SECRET=$Ckpc6ZlGF*Z3vJ89Nr
```

### CODE REVIEW

**Review by joeycor92 — APPROVED** [review]
Looks good. It's ok if jwtSecret is visible?

**Review by DaraghK93 — APPROVED** [review]
looks good, thanks for changing this. a lot more secure now

**Review by caolan-power — APPROVED** [review]
Nice one. Looks good to me

**Comment by WarrenK-design** [comment]
> Looks good. It's ok if jwtSecret is visible?


Few things online have said it doesn't matter too much but before this is merged I may do the same to the JWT just to finalise all this security.

**Review by BearachB — APPROVED** [review]
All looks good @WarrenK-design. Thanks for this, definitely needed to tighten up security wise!

**Comment by joeycor92** [comment]
> > Looks good. It's ok if jwtSecret is visible?
> 
> Few things online have said it doesn't matter too much but before this is merged I may do the same to the JWT just to finalise all this security.

Thanks for updating. Extra secure now!

**Pull request merged**
