### PR TITLE
Pagination 

### PR DESCRIPTION
**Pull request by WarrenK-design**
This PR was supposed ot be full Game name, image and type page hence the branch naming but as spoken about @beckskelly just to keep it smaller only deals with the pagination for the ```createGamePage``` no styling or anything, any scss you can ignore I have tried to delete most of it because I did start on the first page but then deleted it. 

When you click on the create game card on the game page it now takes you to the ```CreateGameScreen``` component.  There is a lot of commented out state at the top but helped me plan out future PR's so left it in for now. 

The ```screen``` state dictates what screen will be shown along with the ```gameType``` state. There is 1 extra screen for a ```valueBased``` game to set the winning value. 

You will get a warning for an unused setter but I need to initialise the state to show pagination working, it will be fixed in next PR. 
image

The ```gameType``` is set to a default of ```valueBased``` for now just to show the flow. 

Each "screen" will be held in the component ```GameCreationOptionsCard``` component which will just render its children components being a card body along with the buttons. 

When you get t the end for now ```Finish``` just does a console log, will eventually be a redirect. 
image

### CODE REVIEW

**Comment by beckskelly** [comment]
Hey @WarrenK-design , looks very good, its a very clever solution and I like your approach for just setting the information in the card. Also appreciate the smaller PR so we can just test the functionality. Just wondering one small thing, the first card, are you going to redirect the user back to /game if they hit the back button in a future PR? You have it disabled for now so I presume you know and are going to sort it out

image

**Comment by WarrenK-design** [comment]
> Hey @WarrenK-design , looks very good, its a very clever solution and I like your approach for just setting the information in the card. Also appreciate the smaller PR so we can just test the functionality. Just wondering one small thing, the first card, are you going to redirect the user back to /game if they hit the back button in a future PR? You have it disabled for now so I presume you know and are going to sort it out
> 
> image

Hi Becks cheers, 

No just going to leave it disabled for now and just have it focused on the game steps, maybe even removing it all together if the user is on page 1, can click just the ```game``` in navbar to get back to that route. 

Sort of bit like this only next button, second ones is apples only "continue" but same flow. 

image
image

**Comment by beckskelly** [comment]
@WarrenK-design grand! Happy to approve, my suggestion is to just get rid of it if the user is on page 1. I was reading Neilsons Heuristics of usability design this week, and no8 states thats basically anything extra that isnt relevant just competes with the other information for visibility. 

https://www.nngroup.com/articles/ten-usability-heuristics/

**Review by beckskelly — APPROVED** [review]

**Review by DaraghK93 — APPROVED** [review]
Looks great Warren, can really see how it's coming together now. one thing to note is that in the backend I've called it "league" and you have it as "game". not sure if you think this will be an issue or not

**Comment by WarrenK-design** [comment]
> Looks great Warren, can really see how it's coming together now. one thing to note is that in the backend I've called it "league" and you have it as "game". not sure if you think this will be an issue or not

Yeah I did notice that in my head was sorta having "Game" is made up of "Leagues" but something we need to be aware of alright.

**Pull request merged**
