### PR TITLE
News card container for stock page

### PR DESCRIPTION
**Pull request by WarrenK-design**
News card container for news articles. Again this needs some work but in some condition to demo tomommow. 

If you want to see news go to Apple stock. 

***Desktop***
image
***Mobile***
image

### CODE REVIEW

**Review by beckskelly — APPROVED** [review]
Looks fine by me, good enough to push for tomorrow. can improve it along with the rest of the page later good to just show something to the lecs

**Comment by WarrenK-design** [comment]
Fixed a few issues on this the pull request was too rushed on Friday. I know we where saying one PR per issue will do in future just on weekend didnt want to bother people and they all sort of tied together. 

**1.[Article Cards](https://github.com/daraghk93/stockapp/issues/339)**
Component - NewsArticleCard.js
Scss - newsArticleCard.scss 
Fixed the sizing of them, removed some information like description. They are now all the same size and images are all the same sizes. If the headline is quite long they are dynamic to adjust but for the most part they are all the same size, images always the same size. 

__Mobile__
image
__Desktop__
image

**2.[Article Container](https://github.com/daraghk93/stockapp/issues/340)**
__Component__ - NewsArticleContainer.js
__Scss__ - newsArticleContainer.scss
Fixed sizing issues with this. Heading for the "News Feed" will stay in place as you scroll though articles. Heading will also appear when there is an error instead of just blank box. 

__Mobile__
image

__Desktop__
image

**3.[Article Modal for More Info](https://github.com/daraghk93/stockapp/issues/349)**
__Component__ -   NewsArticleCard.js
__Scss__ - newsArticleCard.scss 

This is embeddded within each articleCard as the state which controls it belongs to the  NewsArticleCard.js component. This appears when you click on an article card. 

__Mobile__
image

__Desktop__
image

**4.[Sentiment Badge](https://github.com/daraghk93/stockapp/issues/341)**
__Component__ - SentimentBadge.js
__Scss__ - sentimentBadge.scss

Used to indicate the sentiment of a news article of twitter post. changes colour based upon the sentiment of Positive, Negative or Neutral passed to it. 

__Mobile__
image

__Desktop__
image

**5. Layout**
__Component__ - StockPage.js
Have created a new row, I think Twitter and News should be on there own Row. 2 Columns for desktop and 1 column for phones. 
image
image

**Comment by beckskelly** [comment]
Looks well Warren, I like the badge, new container, how it looks in desktop. We'll go with 1PR per issue in the future as you've noted but you have well explained the changes made in your comment.

**Review by caolan-power — APPROVED** [review]
Looks good. I'll see how embedding the tweets looks in that then once this has been merged. Hopefully can use a lot of this

**Comment by beckskelly** [comment]
@WarrenK-design Just noticed youre not using the variables in SCSS, it will make it harder to change it down the line, i'd set these colours as variables using the $ sign at the top of your sheet -


For example 
$neutral-positive: #XXXXXXX 
image

**Review by joeycor92 — CHANGES_REQUESTED** [review]
As mentioned in our discussion, might want to look at the position of the neutral badge and source, but if you've already chatted to the others then that's ok.

There's also an error here that you might want to fix.
image

**Comment by WarrenK-design** [comment]
> As mentioned in our discussion, might want to look at the position of the neutral badge and source, but if you've already chatted to the others then that's ok.
> 
> There's also an error here that you might want to fix. image

Cheers for catching this, should be fixed there in latest commits.

**Review by joeycor92 — APPROVED** [review]
Ok that error is gone and it looks better as well with the bigger neutral badge. Thanks for doing so quickly.

**Pull request merged**
