### PR TITLE
Backend - stock discovery categories - backend controller for displaying companies by sector

### PR DESCRIPTION
**Pull request by DaraghK93**
backend is now calling top E, S, G, sorting them by rating, topGainers, TopLosers, by several sectors (sorted by daily change). There are 11 sectors in total - I haven't added them all yet, just the main ones. 

I've also added this to the stockRouteService file, so it is just called from the stock controller, as it was getting very large
Screenshot 2022-10-25 at 20 47 18

I've added some of them to the frontend stockDiscovery Screen too
Screenshot 2022-10-25 at 20 47 52

Screenshot 2022-10-25 at 20 48 18

Screenshot 2022-10-25 at 20 48 36

### CODE REVIEW

**Review by beckskelly — APPROVED** [review]
Looks good @DaraghK93, a lot of work here behind the scenes. Thanks for this, page looks a lot better now with more content

**Review by beckskelly — CHANGES_REQUESTED** [review]
Ok actually just noticed something odd, on my screen there are no side scroller bars for the bottom categories? 
image

**Comment by DaraghK93** [comment]
Hey, Becks, not sure why that's happening. I've tested it every which way and they're still working for me. Might wait and see what @joeycor92 says

**Review by joeycor92 — APPROVED** [review]
Ok so I can see the side scroller for all of the sections.
image

Other than that, no comment. It's all looking great and just fantastic to see this page coming together.

**Review by beckskelly — APPROVED** [review]
Cool I'll approve so, looks to be some weirdness on my end with the scrollers! Thanks for all the good work

**Pull request merged**
