### PR TITLE
added stockdisvoery page

### PR DESCRIPTION
**Pull request by beckskelly**
Added stock discovery page,
added components for searchbar (not functional) and tickercard
Fixed footer (position relative)
Pulled in stocks from DB to populate tickercards

### CODE REVIEW

**Comment by beckskelly** [comment]
image

**Review by WarrenK-design — CHANGES_REQUESTED** [review]
image
Cant see it in your package.json either?

**Review by WarrenK-design — CHANGES_REQUESTED** [review]
**This is formatted as email** 
image

*****************************************************************************************

**Are we fixing this spacing?** 
image

******************************************************************************************

**Mobile one too**
image

**Review by joeycor92 — CHANGES_REQUESTED** [review]
As mentioned in the messages you might want to change this:
image

We shouldn't be hardcoding the url.

As well, not for now but we need to discuss whether we're using axios or async so that we can be consistent.

**Review by WarrenK-design — APPROVED** [review]
Fixed CSS and API now calls the live API not the localhost when deployed.

**Review by joeycor92 — APPROVED** [review]
This looks great. Thanks @beckskelly for doing the brunt of it and thanks Warren for helping with the CSS and a few bits.

**Pull request merged**
