### PR TITLE
Portfolio page - my balances component

### PR DESCRIPTION
**Pull request by beckskelly**
Late in the evening so theres no need to review this for tomorrow, I can demo on localhost.

Started work on the "My Balances"/ Holdings component
2x views - table view and circle chart view.

Will need to get the circle chart evaluated by a user as its outside the prototype.
Table is just a placeholder table, the logic isnt properly in there to map the holdings to it yet, this is more a general idea for styling.

image
image

### CODE REVIEW

**Review by WarrenK-design — CHANGES_REQUESTED** [review]
Hi Becks looks good just few things. 

I think make the table a default view it will be a lot clearer and to the point.   

# Table
The Balance thing up the top is still a bit confusing it looks like "$50" is a column name. It was something in the user eval too to try make this stand out bit more. Maybe even sepreate it out from the table completely in some way? Still a bit confusing to me. 
image
## Table Style 
I think you know this yourself but maybe white background sort of to fit into theme of the rest the grey stands out. The images too are bit small I think for logos. 
image
## Sorting 
User should be able to sort these in some way, when we get to the stage to have $100,000 to play with there will be a lot in this table. 
image
## Spacing 
Lot of unused space, center the table in the parent div maybe? 
image
On mobile looks a bit squished spacing doesnt seem equal gets less and less? 
image

# Circle Graph 
Its a nice viz but personally I prefer the table a lot more to be honest.  Get it evaluated too before you do anymore on it, I done the eval for this page [here](https://tudublin-my.sharepoint.com/:w:/r/personal/c16463344_mytudublin_ie/_layouts/15/Doc.aspx?sourcedoc=%7BF04C43AA-8D4E-4A51-B73E-A5C95164536A%7D&file=Portfolio_Page_Evaluation_01.docx&action=default&mobileredirect=true) and didn't have it in there at all not 100% sure if its necessary either user seemed to understand table for most part was just the balance thing at the top. 

I have increased the stocks in the portfolio to 12 which is still quite low I think and the viz does start to become unusable/confusing to look at I feel. 
image
Even worse the more we go up. 
image
I do understand probably took a lot of work to do that viz but we do need to think of the usability too :( a really good table may be better and clearer than letting the user select different graphs. 


Also @joeycor92 you may throw your eye on the portfolio dummy data just make sure its what you are planning in backend.

**Comment by beckskelly** [comment]
Great points guys, will have an updated PR tomorrow morning addressing everything.

**Review by joeycor92 — CHANGES_REQUESTED** [review]
Some great stuff here but others I'm not sure about.

You had mentioned that on desktop there would be more information available in the table, it looks a bit bare. Wondering if the collapsible should disappear for the desktop?

Only other thing I see instantly is that the numbers don't seem to be centered in the row.
image

Other than that I think it's ok for me.

**Review by WarrenK-design — CHANGES_REQUESTED** [review]
Hi Becks, 

Small things and to be honest not sure if we have time to fix second but I think just something should be aware of. 

# Balance 
Id miss this scrolling though the page and think its important that it stands out a bit more. 

I think as well there was a discussion on the word "Balance" did we agree on something else for this like "Spending Power", this is the balance the user has available to spend. 
image

# Sizing 
Mobile looks good but we cant throw away desktop altogether. 
image

# Priority 
I know you have mentioned going back to the circle but I'd say the game screen/prototype/evaluation is more important than the sectors viz for you this week. Even the transaction history I'd put above the sectors viz. 

I do get that it is a nice viz but you know yourself with the visualisations they eat up a lot of time, stock graph dates/buttons still need to be done, same thing with this portfolio graph, colours on radar/bar charts and all the other little bits you have been marking in excel. They eat up a lot of time and just worried it might not be worth the time at this stage for a sectors chart. 

Before you start can we discuss it as a team in the discord/at stand up tomorrow, the high priority stuff needs to be focused on now.  

# Reusability 
Again before you do this where does this table need to be reused? If we are only using it for portfolio balances then it is ok the way it is I think now. 

The input is just a Portfolio object and it will work anywhere yeah?

**Comment by beckskelly** [comment]
Hey @joeycor92 and @WarrenK-design, thank you for the reviews!

After reading the reviews and the discussion this morning, I will just fix the "balance" part of the component and move on. This is the general plan for the future as we have to focus on getting functionality out for the game right now.

**Future work**
- extract sorting and pagination logic for transaction history table
- Fix table for desktop

**Nice to haves**
- circle component

**Comment by beckskelly** [comment]
Changed to this, let me know if it can be improved!

image

**Comment by joeycor92** [comment]
> Hey @joeycor92 and @WarrenK-design, thank you for the reviews!
> 
> After reading the reviews and the discussion this morning, I will just fix the "balance" part of the component and move on. This is the general plan for the future as we have to focus on getting functionality out for the game right now.
> 
> **Future work**
> 
> * extract sorting and pagination logic for transaction history table
> * Fix table for desktop
> 
> **Nice to haves**
> 
> * circle component

Another bit of future work is to centre the numbers in the row, they are closer to the top.

**Review by joeycor92 — APPROVED** [review]

**Comment by joeycor92** [comment]
I've approved for now as there are more important elements of the app to be worked on. Great work on this page.

**Comment by beckskelly** [comment]
image


After discussion in discord, heres the final change for the balance

**Review by WarrenK-design — APPROVED** [review]
Yep looks good, again might be of help in future and save time instead of using divs [React Bootsrap Grid](https://react-bootstrap.github.io/layout/grid/) and [Bootsrap Grid](https://getbootstrap.com/docs/4.0/layout/grid/) use flexbox. 

Container may not always be necessary but Row and Col are really handy. 

```
<Container>
   <Row>
        <Col>
        </Col>
     </Row>
</Container>
```

**Pull request merged**
