### PR TITLE
Sprint retrospective Week 5

### PR DESCRIPTION
**Pull request by WarrenK-design**
Written with team on Friday 21st of October for week 5 of the project.

### CODE REVIEW

**Review by BearachB — APPROVED** [review]
Looks good!

**Review by joeycor92 — APPROVED** [review]
That seems to be in line with everything we discussed on Friday. Action-wise I've already started filling out the routes spreadsheet so off to a flier.

**Review by caolan-power — APPROVED** [review]

**Review by beckskelly — APPROVED** [review]
Looks good, nice small retro, just deleted all my branches there so we're on track

**Review by DaraghK93 — APPROVED** [review]
looks Good Warren. off to a good start with these this week anyway

**Pull request merged**
