### PR TITLE
Active games redux state

### PR DESCRIPTION
**Pull request by WarrenK-design**
This PR stores the active portfolios in redux, you need to install [Redux Dev Tools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en) to test this. 

The portfolio state is stored at the moment in the following structure. 
```
portfolios: {
    activePortfolios: [
      {
        _id: '6384e89761ae395e1f97b1af',
        portfolioName: 'Warren\'s Stock Trading Game Portfolio',
        leagueId: '6384e89761ae395e1f97b1ad',
        leagueName: 'Warren\'s Stock Trading Game'
      },
      {
        _id: '6384e8be61ae395e1f97b1b8',
        portfolioName: 'Bear Hunter Society Portfolio',
        leagueId: '6384e8be61ae395e1f97b1b6',
        leagueName: 'Bear Hunter Society'
      }
    ]
  }
```
The action ```updateActivePortfolios``` is only used to update the portfolio state at the moment for the active portfolios, it calls the route ``` GET /api/portfolio/myGamesAndPortfolios```. The action is dispatched when a user goes onto the website (called in App.js useEffect) and when a user creates a game which has ```active``` set to ```true```. 

We will eventually have to call it in other places too like the trade page in case a user tries to make a trade but the  portfolio switches from active to inactive before they finalise the trade. 

# Testing
## No Active Games 
If you have no active games yu should have no active portfolios in state. 
image

## Create an active Game
When you create an active game the state should update. 
image

## Initial State
When you open up the website your active game portfolios should be in state.

### CODE REVIEW

**Review by beckskelly — APPROVED** [review]
Looks good @WarrenK-design , can't see any issues with it on this end anyway, tried logging in, out, created a new user, created new portfolio, all updates in the state in redux. Thanks for this!

**Review by DaraghK93 — APPROVED** [review]
Hi Warren, great work. tried to create each type of portfolio, new user, logged in and out, joined leagues. all worked perfectly, well done

**Review by beckskelly — APPROVED** [review]
Works with the game access code as well, good spot. happy to approve again

**Review by DaraghK93 — APPROVED** [review]
Hi Warren. all good. weird, I thought i'd tested join game the last time but must not have been paying attention. good spot. all fixed now as far as i can tell

**Pull request merged**
