### PR TITLE
deleted old functions and added new express server

### PR DESCRIPTION
**Pull request by DaraghK93**

### CODE REVIEW

**Review by BearachB — COMMENTED** [review]
So we've moved from using "stockfunction" and "articlefunction" to now just using one overall function "expressServer"?

**Review by caolan-power — APPROVED** [review]
Looks good to me

**Comment by caolan-power** [comment]
> So we've moved from using "stockfunction" and "articlefunction" to now just using one overall function "expressServer"?

yeah

**Comment by DaraghK93** [comment]
> So we've moved from using "stockfunction" and "articlefunction" to now just using one overall function "expressServer"?

Yes, exactly

**Pull request merged**
