### PR TITLE
Redux registration page

### PR DESCRIPTION
**Pull request by WarrenK-design**
Redux now working with registration page. Makes POST request to /api/user in the register user action, then logs the user in using the login redux action. 

The state is saved in user -> userInfo in redux and contains info below. 

image

### CODE REVIEW

**Review by DaraghK93 — APPROVED** [review]
looks good. cheers for the clean up. I'll add that validation for nulls

**Review by joeycor92 — CHANGES_REQUESTED** [review]
Looks good except maybe take out the console.log
image

**Comment by WarrenK-design** [comment]
> Looks good except maybe take out the console.log image

Updated there

**Review by joeycor92 — APPROVED** [review]
Thanks for that change.

**Pull request merged**
