### PR TITLE
stock Discovery - search results pagination

### PR DESCRIPTION
**Pull request by DaraghK93**
Stealing Caolan's code here for this as he's done it well for the game stocks.

it just shows 24 per page and desktop has 6 columns, tablet 4 and phone 2.

Screenshot 2022-12-12 at 10 52 23
Screenshot 2022-12-12 at 10 52 33

Screenshot 2022-12-12 at 10 52 48

### CODE REVIEW

**Comment by beckskelly** [comment]
Tiny cosmetic issue on the mobile here @DaraghK93 in that its not cenetered. I can have a go fixing it, @caolan-power is it the same in your stock search page? 
image

**Comment by caolan-power** [comment]
yep it is i'll pull from it when you change. That PR is still up

**Review by beckskelly — APPROVED** [review]
pushed that centering change there daragh so I'll approve

**Comment by caolan-power** [comment]
> pushed that centering change there daragh so I'll approve

Will steal this for the other PR thanks!

**Review by caolan-power — APPROVED** [review]
That's great will use these in my search section Thanks for that

**Pull request merged**
