### PR TITLE
News sentiment graph data

### PR DESCRIPTION
**Pull request by WarrenK-design**
Graphs on the frontnend for new ar now based upon real data in the db. 

The route  GET api/stocks/:symbol was altered so that returned now embedded in the stock returned is the fields below, format was chosen based upon the graphs inputs. (Have also updated spreadsheet [here](https://tudublin-my.sharepoint.com/:x:/r/personal/c16463344_mytudublin_ie/_layouts/15/Doc.aspx?sourcedoc=%7BA378EC28-CA20-4E78-AD21-3DD6DD132B0F%7D&file=API_Route_Specifications.xlsx&action=default&mobileredirect=true)
```
"newsSentiment": [
        {
            "name": "Positive",
            "value": 33
        },
        {
            "name": "Negative",
            "value": 14
        },
        {
            "name": "Neutral",
            "value": 36
        }
    ],
```
The ```chartCard.js``` component also updated if no data is avaialable to plot for ESG, news or twitter a info messsage will display. 
image

Other small update was for removing ```Corporation``` when searching for companies, was for example showing no news for Microsoft as its full name id ```Microsoft Corporation```. News articles also sorted by date now so most up to date ones will appear first.

### CODE REVIEW

**Review by beckskelly — APPROVED** [review]
Looks good @WarrenK-design, I like the new empty card for when there's no data and as discussed in discord it looks well in both desktop amd mobile. Backend looks logical as far as I can see.

Looking over the cards I am definitely going to change them up a bit, do you have an overall sentiment returned for the company? I think that should definitely be included in the cards, along with a little more "at a glance" information but that's more my end of the work.

Thanks for that, looks good

**Comment by WarrenK-design** [comment]
> do you have an overall sentiment returned for the company?
Going to have a service for it yeah moving onto these ticker cards now to get overall sentiment. I can return it in GET /stocks/:api if need it there too? 
image

**Comment by beckskelly** [comment]
@WarrenK-design Sound! yes one for the get all stocks route (for those ticker cards), and one for the individual stocks (for improving the graphs) would be great!

**Review by joeycor92 — APPROVED** [review]
Looks good, except when they only have one type.
image
Anything we can do about that?

Happy to approve for tomorrow.

**Comment by beckskelly** [comment]
@joeycor92 I will look into this next week, the graphs needs a bit of jazzing up anyway

**Pull request merged**
